#!/bin/bash
title=$1
anz=0
do=true
while true; do
    anz=$(wmctrl -l | grep "$title" | wc -l)
    if (( "$anz" == "1" )); then
	do=false
	break
    fi
    sleep 1
done

wmctrl -r "$title" -b add,maximized_vert,maximized_horz
wmctrl -r "$title" -b add,below

winid=$(wmctrl -lx | grep -E "$title" | grep -oE "[0-9a-z]{10}")
winid2=$(echo $winid | awk '{print $1}')
./toggle-decorations $winid2

