#!/bin/bash
anz=0
do=true
while true; do
    anz=$(wmctrl -l | grep webdeskwindow | wc -l)
    if (( "$anz" == "1" )); then
	do=false
	break
    fi
    sleep 1
done

wmctrl -r "webdeskwindow" -b add,maximized_vert,maximized_horz
wmctrl -r "webdeskwindow" -b add,below

winid=$(wmctrl -lx | grep -E "webdeskwindow" | grep -oE "[0-9a-z]{10}")
winid2=$(echo $winid | awk '{print $1}')
./toggle-decorations $winid2

